### PR TITLE
Exclude plugins as default except for Paragraph to match the editorjs pattern

### PR DESCRIPTION
**Pull request by marianrick**
Developed in the discussion here: https://github.com/Jungwoo-An/react-editor-js/issues/4

By default, the editor only supports Paragraphs, all other tools can be added manually.

For this the README was adapted accordingly.

### CODE REVIEW

**Comment by VLZH** [comment]
I think that file `constance.ts` in `/ lib` may to confuse and it would be cool if this file will be in `stories`.

**Comment by marianrick** [comment]
Good hint @VLZH. I wasn't sure how small I should keep the change and didn't want to change too much of the structure. But this was confusing 🙂

**Comment by Jungwoo-An** [comment]
@marianrick Thanks! 😍

I think this pr is awesome.
However, `constant.ts` can't be used because storybook does not add typescript. i think it better to change the extension to `js`.

**Comment by marianrick** [comment]
Hi @Jungwoo-An, thanks for the review. You are absolutely right. I have changed the extension to `js` 🙂 

(It may be smart to squash the comments when merging it)

**Comment by Jungwoo-An** [comment]
🎉 Awesome! Thanks for your first contribute @marianrick

This request to publish to v1.4.0 (minor: break changes)

**Pull request merged**
